version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - amazonwebservices
  - bierner
  - distroless
  - esac
  - ldflags
  - nonroot
  - pipefail
  - trixie
ignoreWords: []
import: []
